# named list of all robots
robots:
  # cf:
  #   enabled: false
  #   uri: radio://0/80/2M/E7E7E7E7E7
  #   # uri: udp://0.0.0.0:19850
  #   # uri: usb://0
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf  # see robot_types
  #   # firmware_params:
  #   #   kalman:
  #   #     pNAcc_xy: 1.0 # default 0.5

  cf2:
    enabled: true
    uri: udp://0.0.0.0:19850
    initial_position: [0.0, 0.0, 0.0]
    type: cf_sim  # see robot_types


# Definition of the various robot types
robot_types:
  cf_sim:
    motion_capture:
      enabled: false
      # only if enabled; see motion_capture.yaml
      # marker: default_single_marker
      # dynamics: default
    big_quad: false
    # battery:
    #   voltage_warning: 3.8  # V
    #   voltage_critical: 3.7 # V
    firmware_logging:
      enabled: true
      default_topics:
        pose:
          frequency: 100
      custom_topics:
        MJ_velocity:
          frequency: 100
          vars: ["kalman.statePX", "kalman.statePY", "kalman.statePZ"]   
        MJ_Command_thrust:
          frequency: 100 # Hz
          vars: [controller.cmd_thrust]

# global settings for all robots
all:
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 1 # 1: PID, 2: mellinger
    locSrv:
      extPosStdDev: 0.001
      extQuatStdDev: 0.05
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 1 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats